# kitty configuration

font_family      JetBrains Mono NF Semi Bold
bold_font        JetBrains Mono NF Extra Bold
italic_font      JetBrains Mono NF Semi Bold Italic
bold_italic_font JetBrains Mono NF Extra Bold Italic
font_size        12.0

background_opacity 0.85
dynamic_background_opacity yes

window_padding_width 8
window_margin_width 0
single_window_margin_width -1
window_border_width 0pt
draw_minimal_borders yes
window_resize_step_cells 2
window_resize_step_lines 2
placement_strategy center
active_border_color none

tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}"

foreground              #CDD6F4
background              #1E1E2E
selection_foreground    #F5E0DC
selection_background    #61c49e

color0  #45475A
color1  #F38BA8
color2  #A6E3A1
color3  #F9E2AF
color4  #89B4FA
color5  #F5C2E7
color6  #94E2D5
color7  #BAC2DE
color8  #585B70
color9  #F38BA8
color10 #A6E3A1
color11 #F9E2AF
color12 #89B4FA
color13 #F5C2E7
color14 #94E2D5
color15 #A6ADC8

cursor            #61c49e
cursor_text_color #F5E0DC

url_color #61c49e

repaint_delay 10
input_delay 3
sync_to_monitor yes

shell_integration enabled
allow_remote_control yes
listen_on unix:/tmp/kitty